defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "default"

theme: jekyll-theme-slate
markdown: kramdown

kramdown:
  input: GFM
  hard_wrap: false

highlighter: rouge
